name: Deploy

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 * *'  # Keep it up-to-date automatically

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push containers
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/realorangeone/slides:latest
